# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/33064/OneDrive/Desktop/prj-main-2/project_1/project_1.runs/synth_1/.Xil/Vivado-19000-a/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xcvc1802-viva1596-1LHP-i-L
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/ber.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/decision.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/delay_line.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_E.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_IP.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_IP1.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_P.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_PC1.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_PC2.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_S.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_feistel.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_key_schedule.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/des/des_round.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/interpolation.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/interpolation_unit.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/rc_filter.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/rom.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/rx.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/tx.v
      C:/Users/33064/OneDrive/Desktop/prj-main-2/rtl/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/33064/OneDrive/Desktop/prj-main-2/project_1/project_1.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/33064/OneDrive/Desktop/prj-main-2/project_1/project_1.runs/synth_1/.Xil/Vivado-19000-a/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
